# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build_test
  displayName: Build stage
  jobs:  
  - job: Build 
    displayName: Build and Push Container Images
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        ls -al
        rm -f README.md
      displayName: step1       
        
    - script: |
        ls -al
        rm -f README.md
        sleep 1
      displayName: step2

  - job: test 
    displayName: test img
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        ls -al
      displayName: test
      
  - job: test_fail
    displayName: test fail
    dependsOn: test
    condition: failed()
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo test is failed
      displayName: test failed

  - job: test_success
    displayName: test success
    dependsOn: test
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo test is success
      displayName: test success 

- stage: deploy 
  displayName: deploy stage
  jobs:  
  - job: deploy 
    displayName: deploy 1st appp
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: abcxyz
      displayName: step1   
    - script: |
        whoami
        printenv
      displayName: step2
